- hosts: my-vm-for-test.westeurope.cloudapp.azure.com
  tasks:
  - name: Re-create a redis container
      docker_container:
      name: example-app
      image: atabbakh/example-app
      state: present
      recreate: yes
  - name: Restart a container
      docker_container:
      name: example-app
      image: atabbakh/example-app
      state: started
      restart: yes
