- hosts: prod
  tasks:
    - name: Re-create example-app container
      docker_container:
        name: example-app
        image: atabbakh/example-app
        state: present
        recreate: yes
    - name: Restart a container
      docker_container:
        name: example-app
        image: atabbakh/example-app
        state: started
        restart: yes
  roles:
    - role: nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        azure:
          - listen 80
          - location / { proxy_pass http://127.0.0.1:8000; }